image: Visual Studio 2017
platform: 
  x64
skip_commits:
  files:
    - '*.md'
    - '.gitignore'
matrix:
  fast_finish: true
environment:
  matrix:
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
configuration:
  - Debug
  - Release

before_build:
  - cmake.exe -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
